# Test run 2 - Tue Aug 19 19:38:19 UTC 2025
# Command: pytest tests/test_authentication.py -v

============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0 -- /home/dcapps/projects/ldap-admin/venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/dcapps/projects/ldap-admin/tests
plugins: cov-6.2.1, mock-3.14.1, flask-1.3.0
collecting ... ERROR: file or directory not found: tests/test_authentication.py

collected 0 items

============================ no tests ran in 0.00s =============================

# End of test run 2 - Tue Aug 19 19:38:19 UTC 2025
